config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :challenges

  namespace :admin do
    resources :challenges
  end

  root 'challenges#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def admin?
    is_admin
  end
end

app/controllers/admin/challenges_controller.rb
class Admin::ChallengesController < ApplicationController
  before_filter :authenticate_user!, only:[:new, :edit, :create, :update, :destroy]
  before_filter :require_is_admin

  def index
    @challenges = Challenge.all
  end

  def new
    @challenge = Challenge.new
  end

  def show
    @challenge = Challenge.find(params[:id])
  end

  def edit
    @challenge = Product.find(params[:id])
  end

  def create
    @challenge = Challenge.new(challenge_params)

    if @challenge.save
      redirect_to admin_challenges_path
    else
      render :new
    end
  end

  def update
    @challenge = Challenge.find(params[:id])

    if @challenge.update(challenge_params)
      redirect_to admin_challenges_path
    else
      render :edit
    end
  end

  def destroy
    @challenge = Challenge.find(params[:id])

    @challenge.destroy
    redirect_to admin_challenges_path
  end

  private

  def challenge_params
    params.require(:challenge).permit(:title, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_is_admin
    if !current_user.admin?
      flash[:alert] = 'You are not admin'
      redirect_to root_path
    end
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  def index
    @challenges = Challenge.all
  end

  def new
    @challenge = Challenge.new
  end

  def show
    @challenge = Challenge.find(params[:id])
  end

  def edit
    @challenge = Challenge.find(params[:id])
  end

  def create
    @challenge = Challenge.new(challenge_params)

    if @challenge.save
      redirect_to challenges_path
    else
      render :new
    end
  end

  def update
    @challenge = Challenge.find(params[:id])

    if @challenge.update(challenge_params)
      redirect_to challenges_path
    else
      render :edit
    end
  end

  def destroy
    @challenge = Challenge.find(params[:id])

    @challenge.destroy
    redirect_to challenges_path
  end

  private

  def challenge_params
    params.require(:challenge).permit(:title, :description)
  end
end

app/helpers/admin/challenges_helper.rb
module Admin::ChallengesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/admin/challenges/edit.html.erb
<h1>编辑挑战</h1>
<%= simple_form_for [:admin, @challenge] do |f| %>
<%= f.input :title %>
<%= f.description :description %>
<%= f.submit "保存" %>
<% end %>

app/views/admin/challenges/index.html.erb
<div class="pull-right">
  <%= link_to("新建挑战", new_admin_challenge_path, :class => "btn btn-default") %>
</div>

<br><br>
<table class="table table-boldered">
  <thead>
    <td>标题</td>
    <td>描述</td>
  </thead>
  <tbody>
    <% @challenges.each do |challenge| %>
    <tr>
      <td><%= challenge.title %></td>
      <td><%= challenge.description %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/challenges/new.html.erb
<h1>新建挑战</h1>
<%= simple_form_for [:admin, @challenge] do |f| %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.submit "新建" %>
<% end %>

app/views/challenges/index.html.erb
<% @challenges.each do |challenge| %>
  <%= link_to(challenge.title, challenge_path(challenge)) %>
<% end %>

app/views/challenges/show.html.erb
  <h1><%= @challenge.title %></h1>
  <p><%= @challenge.description %></p>

  <%= simple_form_for @challenge do |f| %>
  <%= f.input :answer %>
  <%= f.submit "提交" %>
  <% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center"> Copyright ©2016 多读
    <br>Design by yalin
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">多读</a>
        </div>

        <!-- process steps -->
        <div class="bar-main-container azure">
            <div class="wrap">
                <div class="bar-percentage" data-percentage="46"></div>
                <div class="bar-container">
                    <div class="bar"></div>
                </div>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>多读 - 每周读完一本书</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= yield %>
        </div>
        <%= render "common/footer" %>
    </body>
</html>

app/views/welcome/index.html.erb
<div class="container text-center">


    <input type="radio" class="radio" name="progress" value="five" id="five">
    <label for="five" class="label">5%</label>

    <input type="radio" class="radio" name="progress" value="twentyfive" id="twentyfive" checked>
    <label for="twentyfive" class="label">25%</label>

    <input type="radio" class="radio" name="progress" value="fifty" id="fifty">
    <label for="fifty" class="label">50%</label>

    <input type="radio" class="radio" name="progress" value="seventyfive" id="seventyfive">
    <label for="seventyfive" class="label">75%</label>

    <input type="radio" class="radio" name="progress" value="onehundred" id="onehundred">
    <label for="onehundred" class="label">100%</label>

    <div class="progress">
        <div class="progress-bar"></div>
     </div>

</div>